feat: Revamp user registration mail
fossasia/open-event-server pull request #7416
Opened 2020-11-05 16:53 UTC by codedsun

Fixes #7405 

#### Short description of what this resolves:

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

2020-11-06 21:05 UTC, iamareebjamal commented on app/api/auth.py
> +                html=render_template('email/password_reset_and_verify', **context),
pass context as keyword arguments

2020-11-06 21:05 UTC, iamareebjamal commented on app/api/auth.py
> +                html=render_template('email/password_reset', **context),
pass context as keyword arguments

2020-11-06 21:06 UTC, iamareebjamal commented on app/api/users.py
> +            html=render_template('email/user_register.html', **context),
pass context as keyword arguments

2020-11-06 21:06 UTC, iamareebjamal commented on app/api/auth.py
> +                html=render_template('email/password_change'),
.html missing

2020-11-06 21:06 UTC, iamareebjamal commented on app/api/auth.py
> +                html=render_template('email/password_reset', **context),
.html missing

2020-11-06 21:06 UTC, iamareebjamal commented on app/api/auth.py
> +                html=render_template('email/password_reset_and_verify', **context),
.html missing

2020-11-06 21:07 UTC, iamareebjamal commented on app/templates/email/password_reset.html
> +<br/><a href='{link}' target='_blank'>{{ link }}</a>
```suggestion
<br/>{{ link }}
```

2020-11-06 21:07 UTC, iamareebjamal commented on app/templates/email/password_reset_and_verify.html
> +<br> <a href='{link}' target='_blank'> {{ link }} </a>
```suggestion
<br>{{ link }}
```

2020-11-07 10:14 UTC, codedsun commented
@iamareebjamal - mo file created.

2020-11-07 10:16 UTC, iamareebjamal commented on app/templates/email/ticket_purchased.html
>  <br/>Name: {{ order.user.full_name }}
_() missing here

2020-11-07 10:16 UTC, iamareebjamal commented on app/templates/email/ticket_purchased_attendee.html
>  <br/>Name: {{ attendees.0.user.full_name }}
_() missing here

2020-11-07 10:17 UTC, iamareebjamal commented on app/templates/email/user_register.html
> +<br/><br/>{{ _('Your account has been created on') }} {{ settings.app_name }}. {{ _('Congratulations! ') }}
```suggestion
<br/><br/>{{ _('Your account has been created on') }} {{ settings.app_name }}. {{ _('Congratulations!') }}
```

2020-11-07 10:18 UTC, iamareebjamal commented on app/templates/email/user_register.html
> +<br/><br/>{{ _('Your login is: {{ email }} ')}}
email should be out of _()

2020-11-07 10:18 UTC, iamareebjamal commented on app/templates/email/user_register.html
> +<br/><br/>{{ settings.app_name }} Team
_() missing here

2020-11-07 11:10 UTC, codedsun commented
@iamareebjamal - While passing context as keyword argument in send_email function , the jinja html template doesn't recognize values and give error object not found.

2020-11-07 11:54 UTC, iamareebjamal commented
You don't pass context as kwarg, you pass contents of context as kwargs

2020-11-07 11:55 UTC, iamareebjamal commented on app/api/users.py
> +            attachments=None,
If attachments is None, then this is not needed

2020-11-07 11:56 UTC, iamareebjamal commented on config.py
> +    LANGUAGES = ['en', 'de', 'fr']
Add all languages present in the translations folder

2020-11-07 11:56 UTC, iamareebjamal commented on babel.cfg
> +[jinja2: app/templates/**.html]
Add python files here as well

2020-11-07 11:57 UTC, iamareebjamal commented on messages.pot
> +# Translations template for PROJECT.
Delete this file

2020-11-07 11:57 UTC, iamareebjamal requested changes
Add required dependencies in requirements

2020-11-07 17:05 UTC, codedsun commented
@iamareebjamal - Done the changes

2020-11-07 20:32 UTC, iamareebjamal commented on requirements/common.txt
> +Flask-Babel=2.0.0
wrong syntax

2020-11-07 20:33 UTC, iamareebjamal commented
Please add a screenshot of the mail you received and fix the build

2020-11-07 20:35 UTC, iamareebjamal commented on requirements/common.txt
> +Flask-Babel=2.0.0
```suggestion
Flask-Babel==2.0.0
```

2020-11-08 06:48 UTC, codedsun commented
@iamareebjamal For every mail we save the text in the `mails` table. Can  i show you what was present there under column message.

```
Hello,
<br/><br/>Sunet Srivastava Event Till March.
<br/><br/>This is your order confirmation. You can download your tickets at : http://eventyay.com/orders/edd5f2a3-c44e-44fd-905b-4019ad975b4f/view
<br/><br/>Order Summary:
<br/>Order: O1604747108-22
<br/>Name: User User
<br/>

    <br/>'Ticket': Free Ticket
    <br/> 'Suneet': 1
    <br/>

<br/>About this event :
<br/>Datum: October 31, 2020 02:10 PM - March 01, 2021 05:00 PM
<br/>Online
<br/><br/>Best regards,
<br/>Open Event Team
<br/>--
<br/>Login to manage your orders at http://eventyay.com
```

2020-11-08 06:49 UTC, iamareebjamal commented
That's in English

2020-11-08 06:51 UTC, iamareebjamal commented
Build is still feeling. Seems like you didn't check the failing build I mentioned

2020-11-08 06:57 UTC, codedsun commented
> Build is still feeling. Seems like you didn't check the failing build I mentioned

I checked, i thought it would be fixed but still failing. Let me fix it again

2020-11-08 07:55 UTC, codedsun commented
@iamareebjamal pytype ci also needs to be fixed?

2020-11-08 07:59 UTC, iamareebjamal commented
Yes

2020-11-08 09:48 UTC, codedsun commented
@iamareebjamal - need your help for pytype issue, i am unable to resolve this. i am not getting what's the issue.

2020-11-08 10:11 UTC, iamareebjamal commented
Disable https://google.github.io/pytype/errors.html#mro-error on `app/instance.py", line 243, in get_locale`

2020-11-08 10:19 UTC, iamareebjamal commented
Please also write the command to extract to pot, merge to po, and generating mo files because I'll need that for testing

2020-11-08 10:27 UTC, codedsun commented
Extracting to pot
`pybabel extract -F babel.cfg -k _l -o app/translations/messages.pot .`

Updating po
` pybabel update -i app/translations/messages.pot -d app/translations`

Generating mo
`pybabel compile -d app/translations`

2020-11-08 11:44 UTC, codedsun commented
@iamareebjamal - Done!

2020-11-08 11:49 UTC, iamareebjamal commented
How did you test the translation was happening?

2020-11-08 11:51 UTC, codedsun commented
> How did you test the translation was happening?

As you sugggested, In the `de` folder I changed the msgStr of Ticket purchased string `Thank you for your ticket order for` to `Suneet Srivastava` 

i changed my browser display language in firefox to German (De), the website was translated to german now. 
I logged in and purchased a ticket. Now in the mails table I gave you the exact text of the message here. 
https://github.com/fossasia/open-event-server/pull/7416#issuecomment-723538229

2020-11-08 11:54 UTC, iamareebjamal commented
OK. Thank you

2020-11-08 12:00 UTC, iamareebjamal commented on app/templates/email/ticket_purchased_attendee.html
> +    <br/>{ _('Quantity') }}: {{ attendee | length }}
{ missing

2020-11-08 12:35 UTC, iamareebjamal approved these changes

2020-11-08 12:36 UTC, merged