feat: Speaker/Session CSV/PDF Export should adhere to filters
fossasia/open-event-server pull request #7975
Opened 2021-05-26 11:30 UTC by sachinchauhan2889

Fixes https://github.com/fossasia/open-event-frontend/issues/6773

Speaker/Session CSV/PDF Export should adhere to filters

required for https://github.com/fossasia/open-event-frontend/pull/7343

2021-06-03 11:08 UTC, ranjitkshah requested changes

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Session.event_id == event_id, Session.deleted_at == None
```suggestion
            Session.event_id == event_id, Session.deleted_at is None
```

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Session.deleted_at == None,
```suggestion
            Session.deleted_at is None,
```

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Speaker.sessions == None,
```suggestion
            Speaker.sessions is None,
```

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Speaker.deleted_at == None,
```suggestion
            Speaker.deleted_at is None,
```

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Speaker.event_id == event_id, Speaker.deleted_at == None
```suggestion
            Speaker.event_id == event_id, Speaker.deleted_at is None
```

2021-06-03 11:08 UTC, ranjitkshah commented on app/api/helpers/tasks.py
> +            Speaker.deleted_at == None,
```suggestion
            Speaker.deleted_at is None,
```

2021-06-03 11:09 UTC, ranjitkshah commented
lgtm fix left! , 
 works!!

2021-06-09 11:47 UTC, ranjitkshah approved these changes

2021-06-09 16:04 UTC, MeghalBisht approved these changes

2021-06-09 17:21 UTC, merged