wip: feat: Add Event "Documents" to the system
fossasia/open-event-server pull request #8015
Opened 2021-06-07 19:40 UTC by ranjitkshah

reqd for [#7335](https://github.com/fossasia/open-event-frontend/issues/7335)

#### Short description of what this resolves:
 added document_enabled field in event model

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

2021-06-07 19:42 UTC, ranjitkshah commented
need to discuss in meeting

2021-06-09 17:10 UTC, sachinchauhan2889 commented
![21](https://user-images.githubusercontent.com/72552281/121398918-82ee2800-c973-11eb-81d9-d1a181f6bd77.png)

We get this error when we try to fetch eventsList after login. 

We did not get error when we are logout and when we fetch a particular event

2021-06-09 17:11 UTC, sachinchauhan2889 commented
cause of this Error.

![20](https://user-images.githubusercontent.com/72552281/121399079-b3ce5d00-c973-11eb-8a1b-16bf49b38a1a.png)


api of event. 
line no 166

2021-06-10 15:08 UTC, ranjitkshah commented
`curl 'http://localhost:5000/v1/users/3/events?include=general-statistics%2Croles.role%2Croles.user%2Ctickets&filter=%5B%7B%22name%22%3A%22state%22%2C%22op%22%3A%22eq%22%2C%22val%22%3A%22published%22%7D%2C%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222021-06-10T15%3A07%3A42.033Z%22%7D%2C%7B%22and%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22le%22%2C%22val%22%3A%222021-06-10T15%3A07%3A42.033Z%22%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22gt%22%2C%22val%22%3A%222021-06-10T15%3A07%3A42.034Z%22%7D%5D%7D%5D%7D%5D&page%5Bsize%5D=10&page%5Bnumber%5D=1&sort=starts-at' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'Accept: application/vnd.api+json' \
  -H 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjMzMzU1NzMsIm5iZiI6MTYyMzMzNTU3MywianRpIjoiNWRkMmU5ZGItY2IxMS00YWFjLTkzNDItNmM0MzMwZDBkZTQ3IiwiZXhwIjoxNjIzNDIxOTczLCJpZGVudGl0eSI6MywiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJjc3JmIjoiY2Q1MDRiZTctODQ5Yy00ZDkyLWFkNjEtYmFiZjE2ZjE3NDdhIn0.8RMiowitXplBsrWzMlGIoz3Ym3O8AVHc5LtKSMyyXe8' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'Content-Type: application/vnd.api+json' \
  -H 'Origin: http://localhost:4200' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:4200/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed`

2021-06-14 17:52 UTC, ranjitkshah commented
@prateekj117 please check

2021-06-14 18:02 UTC, ranjitkshah commented
> @prateekj117 please check

using JSONB() instead of JSONB() in migrations but it is not working

`File "/home/ranjitkshah/opensource/eventyay/open-event-server/migrations/versions/rev-2021-06-08-00:18:31-66a3114b2317_.py", line 21, in upgrade
    op.add_column('events', sa.Column('document_links', sa.JSONB(), nullable=True))
AttributeError: module 'sqlalchemy' has no attribute 'JSONB'`

2021-06-14 18:05 UTC, ranjitkshah commented
> @prateekj117 please check

using JSONB() instead of JSON() in migrations but it is not working

`File "/home/ranjitkshah/opensource/eventyay/open-event-server/migrations/versions/rev-2021-06-08-00:18:31-66a3114b2317_.py", line 21, in upgrade
    op.add_column('events', sa.Column('document_links', sa.JSONB(), nullable=True))
AttributeError: module 'sqlalchemy' has no attribute 'JSONB'`

2021-06-20 07:46 UTC, prateekj117 requested changes

2021-06-20 07:46 UTC, prateekj117 commented on app/models/event.py
> +    document_links = db.Column(db.JSON)
Import `JSONB` data type `from sqlalchemy.dialects.postgresql import JSONB`. 
Document links column would look like this:
```
document_links = db.Column(JSONB)
```
The schema would probably remain the same.

2021-06-22 19:08 UTC, prateekj117 requested changes

2021-06-22 19:08 UTC, prateekj117 commented on app/api/schema/events.py
> +
Add one more new line here.

Ref: https://www.python.org/dev/peps/pep-0008/#blank-lines

2021-06-24 02:24 UTC, MeghalBisht approved these changes

2021-06-24 15:40 UTC, prateekj117 approved these changes
LGTM !!!

2021-06-24 16:55 UTC, merged