chore: add API docs for role invites/accept role invites
fossasia/open-event-server pull request #8059
Opened 2021-06-25 08:04 UTC by MeghalBisht

Fixes part of https://github.com/fossasia/open-event-server/issues/8052
Fixes https://github.com/fossasia/open-event-server/issues/5775

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

2021-06-28 18:15 UTC, MeghalBisht commented on docs/api/blueprint/role/role_invites.apib
> +
```suggestion
           
           Accept: application/vnd.api+json
           
```

2021-07-17 15:53 UTC, ranjitkshah requested changes

2021-07-17 15:53 UTC, ranjitkshah commented on docs/api/blueprint/role/role_invites.apib
> +            Content-Type: application/json
```suggestion
            Content-Type: application/vnd.api+json
```

2021-07-17 15:53 UTC, ranjitkshah commented on docs/api/blueprint/role/role_invites.apib
> +            Accept: application/vnd.api+json
```suggestion
            Content-Type: application/vnd.api+json
```

2021-11-17 17:42 UTC, ranjitkshah submitted a review, later dismissed

2022-01-08 09:21 UTC, progmatic-99 requested changes
Dredd tests are failing, need to check what's wrong

2022-02-19 09:48 UTC, pc-beast approved these changes

2022-02-19 09:48 UTC, pc-beast approved these changes

2022-02-19 09:49 UTC, merged