feat: add to calender links in ticket purchaser mail
fossasia/open-event-server pull request #8359
Opened 2021-11-08 16:42 UTC by pc-beast

Fixes #8280 
![image](https://user-images.githubusercontent.com/56963647/140782683-33b792a4-da1b-473c-bca5-c9fc13f2ad4b.png)

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

2021-11-08 16:48 UTC, codedsun requested changes

2021-11-08 16:48 UTC, codedsun commented on app/templates/email/ticket_purchased.html
> +<br/>{{ _('Add to calender') }}:    <a href="https://calendar.google.com/calendar/render?action=TEMPLATE&dates={{ order.event.starts_at.strftime('%Y%m%dT%H%M%') }}/{{ order.event.ends_at.strftime('%Y
~Google Calender~ Google Calendar

2021-11-08 16:48 UTC, codedsun commented on app/templates/email/ticket_purchased.html
> +<br/>{{ _('Add to calender') }}:    <a href="https://calendar.google.com/calendar/render?action=TEMPLATE&dates={{ order.event.starts_at.strftime('%Y%m%dT%H%M%') }}/{{ order.event.ends_at.strftime('%Y
Add to Calendar

2021-11-09 08:33 UTC, mariobehling commented
Thank you. Please add a space behind each option as below:
Google • Calendar • iCal • Yahoo • Outlook

2021-11-09 08:34 UTC, mariobehling commented
Also only keep one empty line above "Best regards".

2021-11-09 09:06 UTC, pc-beast commented
![image](https://user-images.githubusercontent.com/56963647/140894922-94ca9078-6ea9-4579-9d6c-7f8cf3e81943.png)

2021-11-09 09:40 UTC, mariobehling approved these changes

2021-11-09 11:05 UTC, codedsun approved these changes

2021-11-09 11:07 UTC, merged