Date time
fossasia/open-event-server pull request #8371
Opened 2021-11-10 18:30 UTC by progmatic-99

Fixes #8337

2021-11-11 10:21 UTC, mariobehling commented
Thanks. Could you please look into the DeepSource test that fails?

2021-11-12 13:26 UTC, progmatic-99 commented
@codedsun @pc-beast please check on your local machines

2021-11-15 02:45 UTC, maze-runnar requested changes

2021-11-15 02:45 UTC, maze-runnar commented on app/api/helpers/mail.py
> +    if not date or not email:
what if `if date and not email`?

2021-11-18 06:50 UTC, pc-beast requested changes

2021-11-18 06:50 UTC, pc-beast commented on app/api/helpers/mail.py
> +            return format_datetime(date, format=fmt, locale=user_locale)
This line can be removed.

2021-11-18 06:50 UTC, pc-beast commented on app/api/helpers/mail.py
> -
Why remove these? Isn't it better to just change the parameters as this is being used repetitively. :thinking:

2021-11-19 18:58 UTC, progmatic-99 commented
**ticket_purchased_organizer email:**
![ss_1637348080](https://user-images.githubusercontent.com/42090582/142676619-30995f20-b841-46ee-bd2f-52d8d8179ee0.png)

**ticket_purchased** email
![ss_1637348113](https://user-images.githubusercontent.com/42090582/142676666-3df7927a-3551-496b-831e-683e36b541c7.png)
![ss_1637348128](https://user-images.githubusercontent.com/42090582/142676683-ab6bd4f5-6253-4290-86ee-aef9320d9a01.png)

**ticket_attendee** pdf
![ss_1637348140](https://user-images.githubusercontent.com/42090582/142676711-c4f91dba-3e85-4977-8d11-175d1a402a99.png)

2021-11-19 20:31 UTC, mariobehling commented
Thanks. I am confused about the example emails. I see the text is in English and the date/time is in German here. As we already translated nearly everything to German I would expect everything to be in German in this example.

2021-11-20 05:24 UTC, progmatic-99 commented
@mariobehling My browser language is set to English, that's why this happened.

**ticket_attendee** mail
![ss_1637385702](https://user-images.githubusercontent.com/42090582/142715508-c8914bd9-67e8-4f7c-b030-4a32e9226d67.png)

**ticket_purchased_organizer** mail
![ss_1637385734](https://user-images.githubusercontent.com/42090582/142715521-f85c6563-751c-4141-812d-8ef1088c6080.png)

2021-11-22 13:28 UTC, mariobehling approved these changes
Looks good for me. Would be good if @maze-runnar could review the changes.

2021-11-22 13:44 UTC, maze-runnar commented
Code changes are ok, but repeated a lot. If we have to convert startsat and endsat so many places, then directly convert them in schema at only one place.

2021-11-22 13:56 UTC, progmatic-99 commented
@maze-runnar In some mails, we need the date part of datetime object, in others we want only time part and in some places we want datetime + timezone info, so for which of the 3 cases I will convert in the schema??

2021-11-22 14:07 UTC, mariobehling commented
@progmatic-99 Could you please change the PR title/commit message to something a bit more meaningful as well? Thank you.

2021-11-22 14:20 UTC, maze-runnar commented
> @maze-runnar In some mails, we need the date part of datetime object, in others we want only time part and in some places we want datetime + timezone info, so for which of the 3 cases I will convert in the schema??

Okay then then this method is ok. We can merge this, and then think of a way to improve it

2021-11-23 18:31 UTC, mariobehling commented
Regarding this
> My browser language is set to English, that's why this happened.

No matter what language your browser is set it will still show in the original language. Only if you activated auto-translate, e.g. in Chrome, then it will show in English or to whatever you have set it. The subject language has nothing to do with the browser. The email is sent out by the server and needs to be solved in the server.

2021-11-24 12:17 UTC, progmatic-99 commented
There is a different issue #8333 for subjects of mails. This can be merged @mariobehling @pc-beast @codedsun

2021-11-25 14:48 UTC, pc-beast approved these changes

2021-11-25 14:49 UTC, pc-beast commented
@mariobehling can be merged now

2021-11-25 14:55 UTC, codedsun approved these changes

2021-11-28 14:45 UTC, merged