fix-9075: Remove empty line, add - in format jinja2 to remove empty l…
fossasia/open-event-server pull request #9091
Opened 2023-10-13 05:00 UTC by lthanhhieu

…ine if do not have data

Fixes #9075 

#### Short description of what this resolves:

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

2023-10-15 17:35 UTC, cweitat commented
@lthanhhieu pls show a screenshot/pdf of the printed badge

2023-10-15 23:08 UTC, mariobehling requested changes
There are "Multiple Migration Heads". Please resolve.

2023-10-22 17:58 UTC, marcoag commented on app/api/custom/check_in_stats.py
I understand from the description that this PR fixes the extra empty line on QR codes for checkin attendees. But the modifications on this file seem related to check-in stats. Just trying to understand, could you explain how this changes are related? thanks in advance!

2023-10-23 03:56 UTC, lthanhhieu commented on app/api/custom/check_in_stats.py
that merge from this branch https://github.com/lthanhhieu/open-event-server/tree/lthanhhieu-tma/feature-9077 to fix issue in UT Test.

2023-10-23 04:31 UTC, norbusan commented on app/api/custom/check_in_stats.py
So this is the combination of two PR/feature branches?
That is not good, please separate them or do them one by one, otherwise we cannot reasonably review code.

2023-10-23 06:40 UTC, lthanhhieu commented on app/api/custom/check_in_stats.py
please review the PR 9077 first, after that I will change this PR as well.

2024-03-19 03:57 UTC, closed without merging